/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * Request message for `UploadFeedbackArtifact`.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaUploadArtifactRequest extends com.google.api.client.json.GenericJson {

  /**
   * Required. Artifact to upload
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GdataMedia artifact;

  /**
   * Required. Type of feedback artifact
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String type;

  /**
   * Required. Artifact to upload
   * @return value or {@code null} for none
   */
  public GdataMedia getArtifact() {
    return artifact;
  }

  /**
   * Required. Artifact to upload
   * @param artifact artifact or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaUploadArtifactRequest setArtifact(GdataMedia artifact) {
    this.artifact = artifact;
    return this;
  }

  /**
   * Required. Type of feedback artifact
   * @return value or {@code null} for none
   */
  public java.lang.String getType() {
    return type;
  }

  /**
   * Required. Type of feedback artifact
   * @param type type or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaUploadArtifactRequest setType(java.lang.String type) {
    this.type = type;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaUploadArtifactRequest set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaUploadArtifactRequest) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaUploadArtifactRequest clone() {
    return (GoogleFirebaseApptestersV1alphaUploadArtifactRequest) super.clone();
  }

}
