/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * The response object for the ListReleases call
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaListReleasesResponse extends com.google.api.client.json.GenericJson {

  /**
   * A token which can be sent as `page_token` to retrieve the next page If this field is omitted,
   * there are no subsequent pages
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nextPageToken;

  /**
   * List of releases
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleFirebaseApptestersV1alphaRelease> releases;

  static {
    // hack to force ProGuard to consider GoogleFirebaseApptestersV1alphaRelease used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleFirebaseApptestersV1alphaRelease.class);
  }

  /**
   * A token which can be sent as `page_token` to retrieve the next page If this field is omitted,
   * there are no subsequent pages
   * @return value or {@code null} for none
   */
  public java.lang.String getNextPageToken() {
    return nextPageToken;
  }

  /**
   * A token which can be sent as `page_token` to retrieve the next page If this field is omitted,
   * there are no subsequent pages
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaListReleasesResponse setNextPageToken(java.lang.String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  /**
   * List of releases
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleFirebaseApptestersV1alphaRelease> getReleases() {
    return releases;
  }

  /**
   * List of releases
   * @param releases releases or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaListReleasesResponse setReleases(java.util.List<GoogleFirebaseApptestersV1alphaRelease> releases) {
    this.releases = releases;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaListReleasesResponse set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaListReleasesResponse) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaListReleasesResponse clone() {
    return (GoogleFirebaseApptestersV1alphaListReleasesResponse) super.clone();
  }

}
