/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * A representation of the testers device
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaDevice extends com.google.api.client.json.GenericJson {

  /**
   * Uri to enroll the iOS device as a part of the apple OTA profile enrollment. Only present if the
   * device is an iOS device and we don't already know its udid
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String enrollIosDeviceUri;

  /**
   * Manufacturer
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String manufacturer;

  /**
   * Model
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String model;

  /**
   * The name of the device Format: devices/{device}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * OS version
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String osVersion;

  /**
   * Platform
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String platform;

  /**
   * The unique device identifier (iOS only)
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String udid;

  /**
   * The user agent string from the browser (passed along in the proxy call).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String useragent;

  /**
   * Uri to enroll the iOS device as a part of the apple OTA profile enrollment. Only present if the
   * device is an iOS device and we don't already know its udid
   * @return value or {@code null} for none
   */
  public java.lang.String getEnrollIosDeviceUri() {
    return enrollIosDeviceUri;
  }

  /**
   * Uri to enroll the iOS device as a part of the apple OTA profile enrollment. Only present if the
   * device is an iOS device and we don't already know its udid
   * @param enrollIosDeviceUri enrollIosDeviceUri or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setEnrollIosDeviceUri(java.lang.String enrollIosDeviceUri) {
    this.enrollIosDeviceUri = enrollIosDeviceUri;
    return this;
  }

  /**
   * Manufacturer
   * @return value or {@code null} for none
   */
  public java.lang.String getManufacturer() {
    return manufacturer;
  }

  /**
   * Manufacturer
   * @param manufacturer manufacturer or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setManufacturer(java.lang.String manufacturer) {
    this.manufacturer = manufacturer;
    return this;
  }

  /**
   * Model
   * @return value or {@code null} for none
   */
  public java.lang.String getModel() {
    return model;
  }

  /**
   * Model
   * @param model model or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setModel(java.lang.String model) {
    this.model = model;
    return this;
  }

  /**
   * The name of the device Format: devices/{device}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the device Format: devices/{device}
   * @param name name or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * OS version
   * @return value or {@code null} for none
   */
  public java.lang.String getOsVersion() {
    return osVersion;
  }

  /**
   * OS version
   * @param osVersion osVersion or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setOsVersion(java.lang.String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Platform
   * @return value or {@code null} for none
   */
  public java.lang.String getPlatform() {
    return platform;
  }

  /**
   * Platform
   * @param platform platform or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setPlatform(java.lang.String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * The unique device identifier (iOS only)
   * @return value or {@code null} for none
   */
  public java.lang.String getUdid() {
    return udid;
  }

  /**
   * The unique device identifier (iOS only)
   * @param udid udid or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setUdid(java.lang.String udid) {
    this.udid = udid;
    return this;
  }

  /**
   * The user agent string from the browser (passed along in the proxy call).
   * @return value or {@code null} for none
   */
  public java.lang.String getUseragent() {
    return useragent;
  }

  /**
   * The user agent string from the browser (passed along in the proxy call).
   * @param useragent useragent or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaDevice setUseragent(java.lang.String useragent) {
    this.useragent = useragent;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaDevice set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaDevice) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaDevice clone() {
    return (GoogleFirebaseApptestersV1alphaDevice) super.clone();
  }

}
