/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * A representation of an app.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaTesterApp extends com.google.api.client.json.GenericJson {

  /**
   * The bundle identifier of the app
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String bundleId;

  /**
   * Tester has consented to share the device's data for the app
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean consented;

  /**
   * Developer contact email for testers to reach out to about privacy or support issues.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String contactEmail;

  /**
   * Display name of the app
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String display;

  /**
   * URL of app icon
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String iconUrl;

  /**
   * The name of the tester app to retrieve Format: devices/{device}/testerApps/{tester_app}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The platform of the app (iOS or Android)
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String platform;

  /**
   * Number of releases for the app
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer releaseCount;

  /**
   * The bundle identifier of the app
   * @return value or {@code null} for none
   */
  public java.lang.String getBundleId() {
    return bundleId;
  }

  /**
   * The bundle identifier of the app
   * @param bundleId bundleId or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setBundleId(java.lang.String bundleId) {
    this.bundleId = bundleId;
    return this;
  }

  /**
   * Tester has consented to share the device's data for the app
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getConsented() {
    return consented;
  }

  /**
   * Tester has consented to share the device's data for the app
   * @param consented consented or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setConsented(java.lang.Boolean consented) {
    this.consented = consented;
    return this;
  }

  /**
   * Developer contact email for testers to reach out to about privacy or support issues.
   * @return value or {@code null} for none
   */
  public java.lang.String getContactEmail() {
    return contactEmail;
  }

  /**
   * Developer contact email for testers to reach out to about privacy or support issues.
   * @param contactEmail contactEmail or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setContactEmail(java.lang.String contactEmail) {
    this.contactEmail = contactEmail;
    return this;
  }

  /**
   * Display name of the app
   * @return value or {@code null} for none
   */
  public java.lang.String getDisplay() {
    return display;
  }

  /**
   * Display name of the app
   * @param display display or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setDisplay(java.lang.String display) {
    this.display = display;
    return this;
  }

  /**
   * URL of app icon
   * @return value or {@code null} for none
   */
  public java.lang.String getIconUrl() {
    return iconUrl;
  }

  /**
   * URL of app icon
   * @param iconUrl iconUrl or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setIconUrl(java.lang.String iconUrl) {
    this.iconUrl = iconUrl;
    return this;
  }

  /**
   * The name of the tester app to retrieve Format: devices/{device}/testerApps/{tester_app}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the tester app to retrieve Format: devices/{device}/testerApps/{tester_app}
   * @param name name or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * The platform of the app (iOS or Android)
   * @return value or {@code null} for none
   */
  public java.lang.String getPlatform() {
    return platform;
  }

  /**
   * The platform of the app (iOS or Android)
   * @param platform platform or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setPlatform(java.lang.String platform) {
    this.platform = platform;
    return this;
  }

  /**
   * Number of releases for the app
   * @return value or {@code null} for none
   */
  public java.lang.Integer getReleaseCount() {
    return releaseCount;
  }

  /**
   * Number of releases for the app
   * @param releaseCount releaseCount or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaTesterApp setReleaseCount(java.lang.Integer releaseCount) {
    this.releaseCount = releaseCount;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaTesterApp set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaTesterApp) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaTesterApp clone() {
    return (GoogleFirebaseApptestersV1alphaTesterApp) super.clone();
  }

}
