/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * The representation of an invite link
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaInviteLink extends com.google.api.client.json.GenericJson {

  /**
   * Email domain restriction set by developer. Testers will only be able to accept invite links
   * using an email with this domain.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String domainRestriction;

  /**
   * Whether or not this invite link can be joined (determined by tester limits)
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean joinable;

  /**
   * The name of the invite link Format: inviteLinks/{inviteLink)
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * List of apps that the tester will be invited to after accepting
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleFirebaseApptestersV1alphaTesterApp> testerApps;

  static {
    // hack to force ProGuard to consider GoogleFirebaseApptestersV1alphaTesterApp used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleFirebaseApptestersV1alphaTesterApp.class);
  }

  /**
   * Email domain restriction set by developer. Testers will only be able to accept invite links
   * using an email with this domain.
   * @return value or {@code null} for none
   */
  public java.lang.String getDomainRestriction() {
    return domainRestriction;
  }

  /**
   * Email domain restriction set by developer. Testers will only be able to accept invite links
   * using an email with this domain.
   * @param domainRestriction domainRestriction or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaInviteLink setDomainRestriction(java.lang.String domainRestriction) {
    this.domainRestriction = domainRestriction;
    return this;
  }

  /**
   * Whether or not this invite link can be joined (determined by tester limits)
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getJoinable() {
    return joinable;
  }

  /**
   * Whether or not this invite link can be joined (determined by tester limits)
   * @param joinable joinable or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaInviteLink setJoinable(java.lang.Boolean joinable) {
    this.joinable = joinable;
    return this;
  }

  /**
   * The name of the invite link Format: inviteLinks/{inviteLink)
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * The name of the invite link Format: inviteLinks/{inviteLink)
   * @param name name or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaInviteLink setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * List of apps that the tester will be invited to after accepting
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleFirebaseApptestersV1alphaTesterApp> getTesterApps() {
    return testerApps;
  }

  /**
   * List of apps that the tester will be invited to after accepting
   * @param testerApps testerApps or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaInviteLink setTesterApps(java.util.List<GoogleFirebaseApptestersV1alphaTesterApp> testerApps) {
    this.testerApps = testerApps;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaInviteLink set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaInviteLink) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaInviteLink clone() {
    return (GoogleFirebaseApptestersV1alphaInviteLink) super.clone();
  }

}
