/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapptesters.v1alpha.model;

/**
 * The request object for the AcceptInviteLink call
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Testers API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest extends com.google.api.client.json.GenericJson {

  /**
   * Email address
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * Email address
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * Email address
   * @param email email or {@code null} for none
   */
  public GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  @Override
  public GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest set(String fieldName, Object value) {
    return (GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest) super.set(fieldName, value);
  }

  @Override
  public GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest clone() {
    return (GoogleFirebaseApptestersV1alphaAcceptInviteLinkRequest) super.clone();
  }

}
